INSERT INTO TB_USER(USUARIO, SENHA) VALUES ('Maria', '123');
INSERT INTO TB_USER(USUARIO, SENHA) VALUES ('Caio', 'senha123');

INSERT INTO TB_TODO (TITULO, DESCRICAO, STATUS, DATA_CRIACAO, USUARIO_ENTITY_ID) VALUES ('Adicionando nota 1', 'Descrição nota 1', 'NAO_INICIADO', '2022-11-16 15:31', 1);
INSERT INTO TB_TODO (TITULO, DESCRICAO, STATUS, DATA_CRIACAO, USUARIO_ENTITY_ID) VALUES ('Adicionando nota 2', 'Descrição nota 2', 'FEITO', '2022-11-17 19:36', 2);
